# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='grpc_redis',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntest.proto\x12\ngrpc_redis\">\n\nQueryReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tuser_list\x18\x03 \x03(\t\",\n\x0b\x43ommonReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\rCommonRequest\x12\x10\n\x08stu_name\x18\x01 \x01(\t2\x94\x01\n\x0bUserStorage\x12@\n\tQueryword\x12\x19.grpc_redis.CommonRequest\x1a\x16.grpc_redis.QueryReply\"\x00\x12\x43\n\x0b\x41\x64\x64Sentence\x12\x19.grpc_redis.CommonRequest\x1a\x17.grpc_redis.CommonReply\"\x00\x62\x06proto3'
)




_QUERYREPLY = _descriptor.Descriptor(
  name='QueryReply',
  full_name='grpc_redis.QueryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='grpc_redis.QueryReply.code', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc_redis.QueryReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_list', full_name='grpc_redis.QueryReply.user_list', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=88,
)


_COMMONREPLY = _descriptor.Descriptor(
  name='CommonReply',
  full_name='grpc_redis.CommonReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='grpc_redis.CommonReply.code', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc_redis.CommonReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=134,
)


_COMMONREQUEST = _descriptor.Descriptor(
  name='CommonRequest',
  full_name='grpc_redis.CommonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stu_name', full_name='grpc_redis.CommonRequest.stu_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['QueryReply'] = _QUERYREPLY
DESCRIPTOR.message_types_by_name['CommonReply'] = _COMMONREPLY
DESCRIPTOR.message_types_by_name['CommonRequest'] = _COMMONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryReply = _reflection.GeneratedProtocolMessageType('QueryReply', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREPLY,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_redis.QueryReply)
  })
_sym_db.RegisterMessage(QueryReply)

CommonReply = _reflection.GeneratedProtocolMessageType('CommonReply', (_message.Message,), {
  'DESCRIPTOR' : _COMMONREPLY,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_redis.CommonReply)
  })
_sym_db.RegisterMessage(CommonReply)

CommonRequest = _reflection.GeneratedProtocolMessageType('CommonRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMONREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_redis.CommonRequest)
  })
_sym_db.RegisterMessage(CommonRequest)



_USERSTORAGE = _descriptor.ServiceDescriptor(
  name='UserStorage',
  full_name='grpc_redis.UserStorage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=172,
  serialized_end=320,
  methods=[
  _descriptor.MethodDescriptor(
    name='Queryword',
    full_name='grpc_redis.UserStorage.Queryword',
    index=0,
    containing_service=None,
    input_type=_COMMONREQUEST,
    output_type=_QUERYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddSentence',
    full_name='grpc_redis.UserStorage.AddSentence',
    index=1,
    containing_service=None,
    input_type=_COMMONREQUEST,
    output_type=_COMMONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSTORAGE)

DESCRIPTOR.services_by_name['UserStorage'] = _USERSTORAGE

# @@protoc_insertion_point(module_scope)
